export {
  createEncounterCatalog,
  DEFAULT_ENCOUNTER_CATALOG,
  getEncounterDefinition,
} from "./catalog";

export {
  acceptEncounterRecovery,
  advanceEncounterEngine,
  canLeaveEncounterStage,
  createEncounterEngineState,
  DEFAULT_ENCOUNTER_RECOVERY_POLICY,
  dismissEncounterRecovery,
  encounterScore,
  getEncounterSafeCorridorStatus,
  getPresentingEncounter,
  reduceEncounterEngine,
  resolveDueEncounterCallbacks,
  resolveEncounter,
  scheduleEncounter,
  skipOptionalEncounter,
  supersedeEncounter,
  supersedeEncounterCallback,
} from "./engine";

export type {
  EncounterAppliedEffect,
  EncounterCallbackDefinition,
  EncounterCallbackStatus,
  EncounterCatalog,
  EncounterClockContext,
  EncounterDefinition,
  EncounterEngineAction,
  EncounterEngineState,
  EncounterFact,
  EncounterFactDefinition,
  EncounterImportance,
  EncounterKind,
  EncounterMemory,
  EncounterMemoryDefinition,
  EncounterOptionDefinition,
  EncounterOutcomeDefinition,
  EncounterRecoveryHook,
  EncounterRecoveryPolicy,
  EncounterRecoveryStatus,
  EncounterRelationship,
  EncounterRelationshipChangeDefinition,
  EncounterResolution,
  EncounterSafeCorridor,
  EncounterSafeCorridorStatus,
  EncounterScheduleRequest,
  EncounterScoreEffectDefinition,
  EncounterStoryLogEntry,
  EncounterTransaction,
  EncounterTransactionStatus,
  ScheduledEncounterCallback,
} from "./types";
