import type {
  ChildhoodChoiceDefinition,
  ChildhoodCompanion,
  ChildhoodFriendCatalogEntry,
  ChildhoodStageDefinition,
  ChildhoodStageId,
} from "./types";

export const CHILDHOOD_STAGE_DEFINITIONS: readonly ChildhoodStageDefinition[] =
  Object.freeze([
    Object.freeze({
      stageId: "toddler-v1",
      label: "Toddler",
      summary: "Small steps, shared play, and the first friendships.",
      startAgeMonths: 18,
      endAgeMonths: 48,
      durationTicks: 90,
      majorChoiceTick: 32,
      settingId: "family-playroom",
    }),
    Object.freeze({
      stageId: "early-childhood-v1",
      label: "Early Childhood",
      summary: "Preschool days turn curiosity into shared adventures.",
      startAgeMonths: 48,
      endAgeMonths: 72,
      durationTicks: 90,
      majorChoiceTick: 34,
      settingId: "neighborhood-preschool",
    }),
    Object.freeze({
      stageId: "elementary-school-v1",
      label: "Elementary School",
      summary: "Learning, teamwork, and confidence grow side by side.",
      startAgeMonths: 72,
      endAgeMonths: 132,
      durationTicks: 150,
      majorChoiceTick: 58,
      settingId: "elementary-campus",
    }),
    Object.freeze({
      stageId: "middle-school-v1",
      label: "Middle School",
      summary: "New independence arrives without deciding the whole future.",
      startAgeMonths: 132,
      endAgeMonths: 168,
      durationTicks: 120,
      majorChoiceTick: 46,
      settingId: "middle-school-campus",
    }),
  ]);

export const CHILDHOOD_STAGE_BY_ID: Readonly<
  Record<ChildhoodStageId, ChildhoodStageDefinition>
> = Object.freeze(
  Object.fromEntries(
    CHILDHOOD_STAGE_DEFINITIONS.map((definition) => [
      definition.stageId,
      definition,
    ]),
  ) as Record<ChildhoodStageId, ChildhoodStageDefinition>,
);

export const CHILDHOOD_FRIEND_CATALOG: readonly ChildhoodFriendCatalogEntry[] =
  Object.freeze([
    Object.freeze({
      personId: "friend-mina-park-v1",
      givenName: "Mina",
      familyName: "Park",
      displayName: "Mina Park",
      gender: "female",
      pronouns: "she-her",
      appearance: Object.freeze({
        heritageStyleId: "asian",
        skinToneId: "golden",
        hairStyleId: "twin-buns",
        hairColorId: "black",
        clothingStyleId: "pinafore-layer",
        clothingPaletteId: "coral-teal",
        shoeStyleId: "velcro-sneakers",
        bagStyleId: "mini-backpack",
        accessoryId: "star-hairclip",
        bodyPresentationId: "girl-child",
        appearanceSignature: "asian-f-twin-buns-coral-pinafore-star",
      }),
    }),
    Object.freeze({
      personId: "friend-mei-chen-v1",
      givenName: "Mei",
      familyName: "Chen",
      displayName: "Mei Chen",
      gender: "female",
      pronouns: "she-her",
      appearance: Object.freeze({
        heritageStyleId: "asian",
        skinToneId: "peach",
        hairStyleId: "soft-bob-clip",
        hairColorId: "dark-brown",
        clothingStyleId: "cardigan-skirt",
        clothingPaletteId: "berry-cream",
        shoeStyleId: "canvas-sneakers",
        bagStyleId: "school-backpack",
        accessoryId: "round-glasses",
        bodyPresentationId: "girl-child",
        appearanceSignature: "asian-f-bob-berry-cardigan-glasses",
      }),
    }),
    Object.freeze({
      personId: "friend-hana-sato-v1",
      givenName: "Hana",
      familyName: "Sato",
      displayName: "Hana Sato",
      gender: "female",
      pronouns: "she-her",
      appearance: Object.freeze({
        heritageStyleId: "asian",
        skinToneId: "porcelain-warm",
        hairStyleId: "high-ponytail",
        hairColorId: "black",
        clothingStyleId: "sporty-shorts",
        clothingPaletteId: "mint-navy",
        shoeStyleId: "sport-trainers",
        bagStyleId: "crossbody-satchel",
        accessoryId: "friendship-bracelet",
        bodyPresentationId: "girl-child",
        appearanceSignature: "asian-f-ponytail-mint-sport-bracelet",
      }),
    }),
    Object.freeze({
      personId: "friend-leo-nguyen-v1",
      givenName: "Leo",
      familyName: "Nguyen",
      displayName: "Leo Nguyen",
      gender: "male",
      pronouns: "he-him",
      appearance: Object.freeze({
        heritageStyleId: "asian",
        skinToneId: "tan",
        hairStyleId: "side-part-crop",
        hairColorId: "black",
        clothingStyleId: "bright-overalls",
        clothingPaletteId: "sunflower-denim",
        shoeStyleId: "velcro-sneakers",
        bagStyleId: "none",
        accessoryId: "sun-cap",
        bodyPresentationId: "boy-child",
        appearanceSignature: "asian-m-sidepart-sunflower-overalls-cap",
      }),
    }),
    Object.freeze({
      personId: "friend-jun-park-v1",
      givenName: "Jun",
      familyName: "Park",
      displayName: "Jun Park",
      gender: "male",
      pronouns: "he-him",
      appearance: Object.freeze({
        heritageStyleId: "asian",
        skinToneId: "golden",
        hairStyleId: "tousled-crop",
        hairColorId: "dark-brown",
        clothingStyleId: "hoodie-chinos",
        clothingPaletteId: "sky-caramel",
        shoeStyleId: "canvas-sneakers",
        bagStyleId: "school-backpack",
        accessoryId: "leaf-pin",
        bodyPresentationId: "boy-child",
        appearanceSignature: "asian-m-tousled-sky-hoodie-leaf",
      }),
    }),
    Object.freeze({
      personId: "friend-arun-patel-v1",
      givenName: "Arun",
      familyName: "Patel",
      displayName: "Arun Patel",
      gender: "male",
      pronouns: "he-him",
      appearance: Object.freeze({
        heritageStyleId: "asian",
        skinToneId: "warm-brown",
        hairStyleId: "curly-crop",
        hairColorId: "black",
        clothingStyleId: "knit-vest-trousers",
        clothingPaletteId: "forest-sand",
        shoeStyleId: "ankle-boots",
        bagStyleId: "crossbody-satchel",
        accessoryId: "round-glasses",
        bodyPresentationId: "boy-child",
        appearanceSignature: "asian-m-curly-forest-knit-glasses",
      }),
    }),
    Object.freeze({
      personId: "friend-emma-brooks-v1",
      givenName: "Emma",
      familyName: "Brooks",
      displayName: "Emma Brooks",
      gender: "female",
      pronouns: "she-her",
      appearance: Object.freeze({
        heritageStyleId: "western",
        skinToneId: "peach",
        hairStyleId: "braided-pigtails",
        hairColorId: "auburn",
        clothingStyleId: "striped-dress",
        clothingPaletteId: "lavender-plum",
        shoeStyleId: "canvas-sneakers",
        bagStyleId: "mini-backpack",
        accessoryId: "star-hairclip",
        bodyPresentationId: "girl-child",
        appearanceSignature: "western-f-braids-lavender-dress-star",
      }),
    }),
    Object.freeze({
      personId: "friend-sofia-rossi-v1",
      givenName: "Sofia",
      familyName: "Rossi",
      displayName: "Sofia Rossi",
      gender: "female",
      pronouns: "she-her",
      appearance: Object.freeze({
        heritageStyleId: "western",
        skinToneId: "tan",
        hairStyleId: "high-ponytail",
        hairColorId: "warm-brown",
        clothingStyleId: "denim-jacket",
        clothingPaletteId: "rust-ocean",
        shoeStyleId: "sport-trainers",
        bagStyleId: "school-backpack",
        accessoryId: "friendship-bracelet",
        bodyPresentationId: "girl-child",
        appearanceSignature: "western-f-ponytail-rust-denim-bracelet",
      }),
    }),
    Object.freeze({
      personId: "friend-chloe-martin-v1",
      givenName: "Chloe",
      familyName: "Martin",
      displayName: "Chloe Martin",
      gender: "female",
      pronouns: "she-her",
      appearance: Object.freeze({
        heritageStyleId: "western",
        skinToneId: "deep-brown",
        hairStyleId: "soft-bob-clip",
        hairColorId: "dark-brown",
        clothingStyleId: "cardigan-skirt",
        clothingPaletteId: "mint-navy",
        shoeStyleId: "ankle-boots",
        bagStyleId: "crossbody-satchel",
        accessoryId: "leaf-pin",
        bodyPresentationId: "girl-child",
        appearanceSignature: "western-f-bob-mint-cardigan-leaf",
      }),
    }),
    Object.freeze({
      personId: "friend-noah-bennett-v1",
      givenName: "Noah",
      familyName: "Bennett",
      displayName: "Noah Bennett",
      gender: "male",
      pronouns: "he-him",
      appearance: Object.freeze({
        heritageStyleId: "western",
        skinToneId: "porcelain-warm",
        hairStyleId: "tousled-crop",
        hairColorId: "warm-brown",
        clothingStyleId: "hoodie-chinos",
        clothingPaletteId: "coral-teal",
        shoeStyleId: "canvas-sneakers",
        bagStyleId: "mini-backpack",
        accessoryId: "none",
        bodyPresentationId: "boy-child",
        appearanceSignature: "western-m-tousled-coral-hoodie-none",
      }),
    }),
    Object.freeze({
      personId: "friend-lucas-moreau-v1",
      givenName: "Lucas",
      familyName: "Moreau",
      displayName: "Lucas Moreau",
      gender: "male",
      pronouns: "he-him",
      appearance: Object.freeze({
        heritageStyleId: "western",
        skinToneId: "golden",
        hairStyleId: "soft-undercut",
        hairColorId: "dark-brown",
        clothingStyleId: "knit-vest-trousers",
        clothingPaletteId: "forest-sand",
        shoeStyleId: "ankle-boots",
        bagStyleId: "school-backpack",
        accessoryId: "round-glasses",
        bodyPresentationId: "boy-child",
        appearanceSignature: "western-m-undercut-forest-knit-glasses",
      }),
    }),
    Object.freeze({
      personId: "friend-mateo-garcia-v1",
      givenName: "Mateo",
      familyName: "Garcia",
      displayName: "Mateo Garcia",
      gender: "male",
      pronouns: "he-him",
      appearance: Object.freeze({
        heritageStyleId: "western",
        skinToneId: "warm-brown",
        hairStyleId: "curly-crop",
        hairColorId: "black",
        clothingStyleId: "sporty-shorts",
        clothingPaletteId: "sunflower-denim",
        shoeStyleId: "sport-trainers",
        bagStyleId: "crossbody-satchel",
        accessoryId: "sun-cap",
        bodyPresentationId: "boy-child",
        appearanceSignature: "western-m-curly-sunflower-sport-cap",
      }),
    }),
  ]);

export const CHILDHOOD_COMPANION_CATALOG: readonly ChildhoodCompanion[] =
  Object.freeze([
    Object.freeze({ companionId: "companion-cat-mochi-v1", kind: "cat", name: "Mochi", coatId: "cream-point", accessoryId: "yellow-bow", personalityId: "gentle" }),
    Object.freeze({ companionId: "companion-cat-mango-v1", kind: "cat", name: "Mango", coatId: "ginger-tabby", accessoryId: "teal-collar", personalityId: "playful" }),
    Object.freeze({ companionId: "companion-cat-pepper-v1", kind: "cat", name: "Pepper", coatId: "tuxedo", accessoryId: "coral-bandana", personalityId: "curious" }),
    Object.freeze({ companionId: "companion-dog-sunny-v1", kind: "dog", name: "Sunny", coatId: "golden", accessoryId: "teal-collar", personalityId: "gentle" }),
    Object.freeze({ companionId: "companion-dog-biscuit-v1", kind: "dog", name: "Biscuit", coatId: "white-caramel", accessoryId: "coral-bandana", personalityId: "playful" }),
    Object.freeze({ companionId: "companion-dog-bean-v1", kind: "dog", name: "Bean", coatId: "black-tan", accessoryId: "yellow-bow", personalityId: "curious" }),
  ]);

const CHILDHOOD_CHOICES: readonly ChildhoodChoiceDefinition[] = Object.freeze([
  {
    choiceId: "childhood-choice-toddler-play-v1",
    stageId: "toddler-v1",
    title: "One favorite toy",
    prompt: "A new playmate reaches for the blocks you love most. What do you do?",
    friendPromptTemplate: "{friend} waits beside the block tower.",
    options: [
      {
        optionId: "toddler-share-blocks-v1",
        label: "Build together",
        description: "Share the blocks and make one big tower.",
        consequencePreview: "More joy and a warmer friendship; this cooperative moment can echo later.",
        effects: [{ scoreId: "happiness", requestedDelta: 4 }],
        relationshipDelta: 8,
        memory: { title: "The shared tower", summary: "You learned that a favorite thing could become more fun when shared.", kind: "friendship", influenceSignals: [{ signalId: "empathy", weight: 2 }, { signalId: "teamwork", weight: 2 }] },
        callback: { callbackId: "callback-shared-blocks-return-v1", dueStageId: "early-childhood-v1", dueStageTick: 22, title: "A tower remembered", story: "Your friend remembers the shared tower and saves a place for you at the building table.", effects: [{ scoreId: "happiness", requestedDelta: 3 }], relationshipDelta: 3 },
      },
      {
        optionId: "toddler-ask-caregiver-v1",
        label: "Ask for gentle help",
        description: "Invite a caregiver to help both of you take turns.",
        consequencePreview: "A calm solution protects wellbeing and later makes asking for help easier.",
        effects: [{ scoreId: "health", requestedDelta: 2 }, { scoreId: "happiness", requestedDelta: 1 }],
        relationshipDelta: 5,
        memory: { title: "Taking turns", summary: "A calm adult helped both children find room in the same game.", kind: "learning", influenceSignals: [{ signalId: "patience", weight: 2 }, { signalId: "confidence", weight: 1 }] },
        callback: { callbackId: "callback-gentle-help-return-v1", dueStageId: "early-childhood-v1", dueStageTick: 22, title: "Help goes both ways", story: "When a puzzle feels difficult, your friend asks you for the same patient help you once found together.", effects: [{ scoreId: "health", requestedDelta: 2 }], relationshipDelta: 2 },
      },
      {
        optionId: "toddler-invent-game-v1",
        label: "Invent another game",
        description: "Turn cushions and ribbons into a new adventure.",
        consequencePreview: "The friendship grows through imagination, with a creative callback later.",
        effects: [{ scoreId: "happiness", requestedDelta: 3 }, { scoreId: "money", requestedDelta: 1 }],
        relationshipDelta: 6,
        memory: { title: "The cushion voyage", summary: "You discovered that imagination could make something new from what was nearby.", kind: "joy", influenceSignals: [{ signalId: "creativity", weight: 2 }, { signalId: "independence", weight: 1 }] },
        callback: { callbackId: "callback-invented-game-return-v1", dueStageId: "early-childhood-v1", dueStageTick: 22, title: "Another small adventure", story: "Your friend brings a cardboard tube and asks what world the two of you should invent today.", effects: [{ scoreId: "happiness", requestedDelta: 2 }, { scoreId: "money", requestedDelta: 1 }], relationshipDelta: 2 },
      },
    ],
  },
  {
    choiceId: "childhood-choice-preschool-welcome-v1",
    stageId: "early-childhood-v1",
    title: "A first day at the art table",
    prompt: "A classmate is new and quiet while everyone chooses a project.",
    friendPromptTemplate: "{friend} looks at the busy art table, unsure where to sit.",
    options: [
      {
        optionId: "preschool-invite-friend-v1",
        label: "Invite them beside you",
        description: "Make room and explain the game together.",
        consequencePreview: "A strong bond now can become dependable teamwork in elementary school.",
        effects: [{ scoreId: "happiness", requestedDelta: 4 }],
        relationshipDelta: 9,
        memory: { title: "A seat at the table", summary: "You noticed someone on the edge and made belonging feel simple.", kind: "friendship", influenceSignals: [{ signalId: "empathy", weight: 2 }, { signalId: "confidence", weight: 1 }] },
        callback: { callbackId: "callback-preschool-invitation-v1", dueStageId: "elementary-school-v1", dueStageTick: 36, title: "A familiar seat", story: "On a crowded first week, your friend waves you toward an open seat and the room feels easier.", effects: [{ scoreId: "happiness", requestedDelta: 4 }], relationshipDelta: 4 },
      },
      {
        optionId: "preschool-build-together-v1",
        label: "Suggest a team project",
        description: "Ask everyone to paint one part of a giant garden.",
        consequencePreview: "Teamwork brings a later invitation to collaborate again.",
        effects: [{ scoreId: "happiness", requestedDelta: 2 }, { scoreId: "money", requestedDelta: -1 }],
        relationshipDelta: 7,
        memory: { title: "The giant paper garden", summary: "Different ideas became one bright picture when everyone had a part.", kind: "learning", influenceSignals: [{ signalId: "teamwork", weight: 2 }, { signalId: "creativity", weight: 1 }] },
        callback: { callbackId: "callback-team-project-v1", dueStageId: "elementary-school-v1", dueStageTick: 36, title: "A project partner", story: "Remembering the paper garden, your friend asks you to join a new classroom project.", effects: [{ scoreId: "happiness", requestedDelta: 2 }], relationshipDelta: 3 },
      },
      {
        optionId: "preschool-give-space-v1",
        label: "Offer supplies, then wait",
        description: "Place paper nearby without demanding an answer.",
        consequencePreview: "A patient friendship grows slowly and returns as quiet trust later.",
        effects: [{ scoreId: "health", requestedDelta: 2 }, { scoreId: "money", requestedDelta: 1 }],
        relationshipDelta: 5,
        memory: { title: "Kindness without pressure", summary: "You learned that giving someone space could also be a form of welcome.", kind: "learning", influenceSignals: [{ signalId: "patience", weight: 2 }, { signalId: "empathy", weight: 1 }] },
        callback: { callbackId: "callback-patient-welcome-v1", dueStageId: "elementary-school-v1", dueStageTick: 36, title: "Quiet trust", story: "Your friend remembers that you never rushed them and chooses you for a calm reading activity.", effects: [{ scoreId: "health", requestedDelta: 2 }, { scoreId: "happiness", requestedDelta: 1 }], relationshipDelta: 3 },
      },
    ],
  },
  {
    choiceId: "childhood-choice-elementary-project-v1",
    stageId: "elementary-school-v1",
    title: "The school discovery fair",
    prompt: "Your group has one week to turn a big question into a small exhibit.",
    friendPromptTemplate: "{friend} opens a notebook and asks how the team should begin.",
    options: [
      {
        optionId: "elementary-research-deeply-v1",
        label: "Research every clue",
        description: "Spend extra evenings checking books and observations.",
        consequencePreview: "Curiosity grows, but the effort costs rest before a later academic echo.",
        effects: [{ scoreId: "health", requestedDelta: -2 }, { scoreId: "happiness", requestedDelta: 2 }],
        relationshipDelta: 6,
        memory: { title: "Questions inside questions", summary: "Following one clue after another made learning feel like exploration.", kind: "learning", influenceSignals: [{ signalId: "curiosity", weight: 2 }, { signalId: "resilience", weight: 1 }] },
        callback: { callbackId: "callback-deep-research-v1", dueStageId: "middle-school-v1", dueStageTick: 30, title: "A question worth revisiting", story: "Your old notes help the two of you recognize a familiar pattern in a harder class project.", effects: [{ scoreId: "happiness", requestedDelta: 3 }], relationshipDelta: 3 },
      },
      {
        optionId: "elementary-coordinate-team-v1",
        label: "Give everyone a role",
        description: "Match tasks to what each teammate enjoys.",
        consequencePreview: "The group feels stronger, and someone later trusts you to bring people together.",
        effects: [{ scoreId: "happiness", requestedDelta: 3 }, { scoreId: "money", requestedDelta: -1 }],
        relationshipDelta: 8,
        memory: { title: "Every voice in the exhibit", summary: "The project worked because different strengths had room to matter.", kind: "friendship", influenceSignals: [{ signalId: "teamwork", weight: 2 }, { signalId: "empathy", weight: 1 }] },
        callback: { callbackId: "callback-team-coordinator-v1", dueStageId: "middle-school-v1", dueStageTick: 30, title: "Trusted with the team", story: "Your friend asks you to help a new club divide a difficult task fairly.", effects: [{ scoreId: "happiness", requestedDelta: 3 }], relationshipDelta: 4 },
      },
      {
        optionId: "elementary-reuse-materials-v1",
        label: "Prototype with reused things",
        description: "Build, fail safely, and rebuild from what is available.",
        consequencePreview: "Resourcefulness saves money and returns as confidence during a later challenge.",
        effects: [{ scoreId: "money", requestedDelta: 4 }, { scoreId: "health", requestedDelta: 1 }],
        relationshipDelta: 6,
        memory: { title: "Built twice, better once", summary: "A failed first version became useful material for a better second one.", kind: "courage", influenceSignals: [{ signalId: "creativity", weight: 2 }, { signalId: "resilience", weight: 2 }] },
        callback: { callbackId: "callback-resourceful-prototype-v1", dueStageId: "middle-school-v1", dueStageTick: 30, title: "Try another version", story: "When a model breaks, your friend remembers the fair and suggests rebuilding instead of quitting.", effects: [{ scoreId: "health", requestedDelta: 2 }, { scoreId: "money", requestedDelta: 2 }], relationshipDelta: 3 },
      },
    ],
  },
  {
    choiceId: "childhood-choice-middle-school-week-v1",
    stageId: "middle-school-v1",
    title: "One free afternoon",
    prompt: "Study, clubs, friends, and rest all want the same afternoon.",
    friendPromptTemplate: "{friend} asks what kind of afternoon the two of you should make.",
    options: [
      {
        optionId: "middle-school-study-pair-v1",
        label: "Study as a pair",
        description: "Work through the hardest lesson, then stop on time.",
        consequencePreview: "A learning habit can reappear in high school, but it does not choose a career for you.",
        effects: [{ scoreId: "health", requestedDelta: -1 }, { scoreId: "happiness", requestedDelta: 2 }],
        relationshipDelta: 7,
        memory: { title: "Hard lessons, shared", summary: "A difficult lesson became manageable when two people explained it differently.", kind: "learning", influenceSignals: [{ signalId: "curiosity", weight: 2 }, { signalId: "patience", weight: 1 }] },
        callback: { callbackId: "callback-study-pair-high-school-v1", dueStageId: "high-school-v1", dueStageTick: 18, title: "The study message", story: "Your friend sends a note before an early high-school exam: work together, then rest. You remain free to choose any future path.", effects: [{ scoreId: "happiness", requestedDelta: 2 }], relationshipDelta: 3 },
      },
      {
        optionId: "middle-school-community-club-v1",
        label: "Help at the community club",
        description: "Set up games and welcome younger children.",
        consequencePreview: "Community confidence returns later as an invitation, never an obligation.",
        effects: [{ scoreId: "happiness", requestedDelta: 4 }, { scoreId: "money", requestedDelta: -1 }],
        relationshipDelta: 8,
        memory: { title: "An afternoon that included everyone", summary: "Helping a mixed-age group have fun made the neighborhood feel closer.", kind: "friendship", influenceSignals: [{ signalId: "empathy", weight: 2 }, { signalId: "confidence", weight: 2 }] },
        callback: { callbackId: "callback-community-club-high-school-v1", dueStageId: "high-school-v1", dueStageTick: 18, title: "An open invitation", story: "The club invites both of you back for a weekend event. It is one opportunity among many, not a fixed identity.", effects: [{ scoreId: "happiness", requestedDelta: 3 }], relationshipDelta: 4 },
      },
      {
        optionId: "middle-school-active-reset-v1",
        label: "Take an active break",
        description: "Walk, play, and talk before the busy week continues.",
        consequencePreview: "Resilience and health improve, and the shared reset is remembered later.",
        effects: [{ scoreId: "health", requestedDelta: 4 }, { scoreId: "happiness", requestedDelta: 2 }],
        relationshipDelta: 6,
        memory: { title: "Room to breathe", summary: "Taking a real break made the next challenge feel less enormous.", kind: "joy", influenceSignals: [{ signalId: "resilience", weight: 2 }, { signalId: "independence", weight: 1 }] },
        callback: { callbackId: "callback-active-reset-high-school-v1", dueStageId: "high-school-v1", dueStageTick: 18, title: "Remember to breathe", story: "During a crowded high-school week, your friend recalls the long walk and suggests a short reset before deciding what comes next.", effects: [{ scoreId: "health", requestedDelta: 3 }], relationshipDelta: 3 },
      },
    ],
  },
] as const);

export const CHILDHOOD_CHOICE_CATALOG: Readonly<
  Record<ChildhoodStageId, ChildhoodChoiceDefinition>
> = Object.freeze(
  Object.fromEntries(
    CHILDHOOD_CHOICES.map((choice) => [choice.stageId, Object.freeze(choice)]),
  ) as Record<ChildhoodStageId, ChildhoodChoiceDefinition>,
);
